[Debug]

# Device-side event tracing (kernel, CU, memory)
device_trace=fine

# Trace delle API XRT lato host
native_xrt_trace=true

# Trace OpenCL runtime
opencl_trace=true


# Dimensione buffer per eventi di trace
trace_buffer_size=100M

continuous_trace=true

[Emulation]

debug_mode=batch
xtlm_aximm_log=true

# Script per loggare tutti i segnali in xsim
user_pre_sim_script= ./debug_all/xsim_all_signals.tcl

