#!/usr/bin/env python3
# verify.py — generated by generate_hacc_project.py, do not edit manually.
# Gathers FPGA output banks into the full tensor and compares to golden reference.
#
# Usage:  python3 verify.py <deploy_dir>
#
# PORT_TO_MQ[port] = (m, q_spatial)
#   m         = filter index (full M, reconstructed from SA spatial mapping)
#   q_spatial = spatial Q index within the SA column fanout (sacols_0)
#
# Gather formula (general for any Q spatial/temporal split):
#   n_rows  = n_op // M        number of spatial Q slots
#   Qtiles  = Q // n_rows      number of temporal Q tile iterations
#   q_full  = q_spatial + n_rows * q_temporal
#   offset  = p * Qtiles + q_temporal  (buffer index within each port)

import glob
import os
import struct
import sys

PORT_TO_MQ = [(0, 0), (1, 0), (0, 1), (1, 1), (0, 2), (1, 2), (0, 3), (1, 3), (0, 4), (1, 4), (0, 5), (1, 5), (2, 0), (3, 0), (2, 1), (3, 1), (2, 2), (3, 2), (2, 3), (3, 3), (2, 4), (3, 4), (2, 5), (3, 5)]
M, P, Q, N_OP = 4, 6, 6, 24


def read_floats(path: str) -> list:
    with open(path, "rb") as f:
        raw = f.read()
    n = len(raw) // 4
    return list(struct.unpack(f"<{n}f", raw))


def main(deploy_dir: str) -> bool:
    in_dir  = os.path.join(deploy_dir, "input_data")
    out_dir = os.path.join(deploy_dir, "output_data")

    # Read golden reference
    gold_path = os.path.join(in_dir, "golden_out.bin")
    if not os.path.exists(gold_path):
        print(f"ERROR: golden not found: {gold_path}")
        sys.exit(1)
    gold = read_floats(gold_path)
    if len(gold) != M * P * Q:
        print(f"ERROR: golden has {len(gold)} floats, expected {M*P*Q}")
        sys.exit(1)

    # Read output banks (sorted numerically: dram_output_p0, p1, ...)
    pattern = os.path.join(out_dir, "dram_output_p*.bin")
    files = sorted(glob.glob(pattern),
                   key=lambda f: int(os.path.basename(f)
                                     .replace("dram_output_p", "")
                                     .replace(".bin", "")))
    if len(files) != N_OP:
        print(f"ERROR: expected {N_OP} output files, found {len(files)}")
        sys.exit(1)
    banks = [read_floats(f) for f in files]

    # Gather — general formula for any spatial/temporal Q split
    n_rows = N_OP // M          # spatial Q slots (sacols_0 dimension)
    Qtiles = Q // n_rows        # temporal Q tile iterations per spatial slot
    floats_per_port = P * Qtiles

    out_full = [0.0] * (M * P * Q)
    for port_idx, (m, q_spatial) in enumerate(PORT_TO_MQ):
        buf = banks[port_idx]
        if len(buf) != floats_per_port:
            print(f"WARNING: port {port_idx} has {len(buf)} floats, expected {floats_per_port}")
        for q_temporal in range(Qtiles):
            q = q_spatial + n_rows * q_temporal
            for p in range(P):
                offset = p * Qtiles + q_temporal
                out_full[m * P * Q + p * Q + q] = buf[offset]

    # Compare
    eps_abs, eps_rel = 1e-3, 1e-3
    errors = 0
    for i in range(M * P * Q):
        diff = abs(out_full[i] - gold[i])
        tol  = eps_abs + eps_rel * abs(gold[i])
        if diff > tol:
            print(f"  MISMATCH at [{i}]: HW={out_full[i]:.6f}  gold={gold[i]:.6f}"
                  f"  diff={diff:.6f}  tol={tol:.6f}")
            errors += 1
            if errors > 20:
                print("  (stopping after 20 errors)")
                break

    print()
    if errors == 0:
        print(f"SUCCESS: all {M*P*Q} outputs match the golden reference.")
    else:
        print(f"FAILURE: {errors} mismatches out of {M*P*Q} outputs.")
    return errors == 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: verify.py <deploy_dir>")
        sys.exit(1)
    ok = main(sys.argv[1])
    sys.exit(0 if ok else 1)
