#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################
# Synthesis script for COMPONENT: top_level
SWD="$(dirname $(readlink -e $0))"

# STEP: vivado_flow
cd $SWD
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source HLS_output/Synthesis/vivado_flow_22/vivado.tcl

