# Copyright (C) 2023 Advanced Micro Devices, Inc.  All rights reserved.

cmake_minimum_required(VERSION 3.16)

###    USER SETTINGS  START    ###
###    DO NOT ADD OR REMOVE VARIABLES FROM THIS SECTION    ###

set(USER_COMPILE_DEFINITIONS
)

set(USER_UNDEFINED_SYMBOLS
)

set(USER_INCLUDE_DIRECTORIES
  "${CMAKE_CURRENT_SOURCE_DIR}/include"
)

set(USER_COMPILE_SOURCES
  "${CMAKE_CURRENT_SOURCE_DIR}/src/support.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/local_support.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/harness.cpp"
)

set(USER_CMAKE_CXX_STANDARD
  17
)

set(USER_COMPILE_WARNINGS_ALL "-Wall")
set(USER_COMPILE_WARNINGS_EXTRA "-Wextra")
set(USER_COMPILE_WARNINGS_AS_ERRORS ""
)
set(USER_COMPILE_WARNINGS_CHECK_SYNTAX_ONLY ""
)
set(USER_COMPILE_WARNINGS_PEDANTIC ""
)
set(USER_COMPILE_WARNINGS_PEDANTIC_AS_ERRORS ""
)
set(USER_COMPILE_WARNINGS_INHIBIT_ALL ""
)

set(USER_COMPILE_OPTIMIZATION_LEVEL "-O0")
set(USER_COMPILE_OPTIMIZATION_OTHER_FLAGS "")

set(USER_COMPILE_DEBUG_LEVEL "-g3")
set(USER_COMPILE_DEBUG_OTHER_FLAGS "")

set(USER_COMPILE_PROFILING_ENABLE "")

set(USER_COMPILE_VERBOSE "")
set(USER_COMPILE_ANSI "")

set(USER_COMPILE_OTHER_FLAGS "-std=c++17")

set(USER_LINK_NO_START_FILES "")
set(USER_LINK_NO_DEFAULT_LIBS "")
set(USER_LINK_NO_STDLIB "")
set(USER_LINK_OMIT_ALL_SYMBOL_INFO "")

set(USER_LINK_LIBRARIES
  xrt_coreutil
  xrt++
  xrt_core
  xilinxopencl
  rt
)

set(USER_LINK_DIRECTORIES
)

set(USER_LINK_OTHER_FLAGS
)

###   END OF USER SETTINGS SECTION ###
###   DO NOT EDIT BEYOND THIS LINE ###

set(USER_COMPILE_OPTIONS
    ${USER_COMPILE_WARNINGS_ALL}
    ${USER_COMPILE_WARNINGS_EXTRA}
    ${USER_COMPILE_WARNINGS_AS_ERRORS}
    ${USER_COMPILE_WARNINGS_CHECK_SYNTAX_ONLY}
    ${USER_COMPILE_WARNINGS_PEDANTIC}
    ${USER_COMPILE_WARNINGS_PEDANTIC_AS_ERRORS}
    ${USER_COMPILE_WARNINGS_INHIBIT_ALL}
    ${USER_COMPILE_OPTIMIZATION_LEVEL}
    ${USER_COMPILE_OPTIMIZATION_OTHER_FLAGS}
    ${USER_COMPILE_DEBUG_LEVEL}
    ${USER_COMPILE_DEBUG_OTHER_FLAGS}
    ${USER_COMPILE_VERBOSE}
    ${USER_COMPILE_ANSI}
    ${USER_COMPILE_OTHER_FLAGS}
)
foreach(entry ${USER_UNDEFINED_SYMBOLS})
    list(APPEND USER_COMPILE_OPTIONS " -U${entry}")
endforeach()

set(USER_LINK_OPTIONS
    ${USER_LINK_NO_START_FILES}
    ${USER_LINK_NO_DEFAULT_LIBS}
    ${USER_LINK_NO_STDLIB}
    ${USER_LINK_OMIT_ALL_SYMBOL_INFO}
    ${USER_LINK_OTHER_FLAGS}
)