"""
gen_verify.py — generate per-deploy verify.py from top_level_sa.c output port table.

The gather formula depends on how M is split across SACols vs SARows — information
that exists at generation time but cannot be reliably re-derived at verify time.
Baking the exact port→(m, q_spatial) table into the deploy folder eliminates this
fragility.

Two C source patterns are handled:
  3D: reduced_output[sarows_1][sacols_0][sacols_1]   ← M split across both SA levels
  2D: reduced_output[sacols_0][sacols_1]              ← M entirely in SACols

In both cases, the resulting table maps port → (m, q_spatial) where:
  q_spatial = sacols_0   (the spatial Q index within the SA column fanout)
  m         = full filter index reconstructed from the M split

The generated verify.py uses a unified gather with:
  n_rows = n_op // M           # number of spatial Q slots (= sacols_0_dim)
  Qtiles = Q // n_rows         # number of Q tile iterations in the outer temporal loop
  q_full  = q_spatial + n_rows * q_temporal
  offset  = p * Qtiles + q_temporal
"""
import re


def parse_output_port_mapping(c_src_path: str) -> list:
    """Return PORT_TO_MQ: list of (m, q_spatial) indexed by port number.

    Parses the output write block from top_level_sa.c.  Handles both:
      3D: dram_output_pN[...] = reduced_output[sarows_1][sacols_0][sacols_1]
      2D: dram_output_pN[...] = reduced_output[sacols_0][sacols_1]
    """
    content = open(c_src_path).read()

    # Try 3D first (M split across SACols AND SARows)
    pat3 = (r'dram_output_p(\d+)\[.*?\]\s*=\s*'
            r'reduced_output\[(\d+)\]\[(\d+)\]\[(\d+)\]')
    entries3: dict = {}
    for port_s, i_s, j_s, k_s in re.findall(pat3, content):
        port = int(port_s)
        if port not in entries3:          # keep first (sub-slot 0 wins)
            entries3[port] = (int(i_s), int(j_s), int(k_s))

    if entries3:
        # 3D: i=sarows_1, j=sacols_0=q_spatial, k=sacols_1
        # Use only the first-seen assignment per port (sub-slot 0 when buffer is written
        # as d*K+0 and d*K+1; sub-slot 0 gives q_spatial from the first row of reduced_output,
        # which pairs correctly with the linear p*Q+q gather when n_rows=1).
        sacols_m = max(k for _, _, k in entries3.values()) + 1
        result: list = [(0, 0)] * len(entries3)
        for port, (i, j, k) in entries3.items():
            result[port] = (i * sacols_m + k, j)   # (m, q_spatial)
        return result

    # Fall back to 2D (M entirely in SACols, no M split in SARows)
    # Use negative lookahead to avoid matching 3D patterns.
    # Keep only the FIRST occurrence per port — when ports are written multiple times
    # (sub-slot packing: dram_output_pN[d*K+0] and [d*K+1]), the first occurrence
    # (sub-slot 0) gives q_spatial=0 for all ports.  The gather formula then produces
    # offset = p*Qtiles + q_temporal = p*Q + q, which matches the actual linear buffer
    # layout for all sub-slot cases with all-M-in-SACols.
    pat2 = (r'dram_output_p(\d+)\[.*?\]\s*=\s*'
            r'reduced_output\[(\d+)\]\[(\d+)\](?!\s*\[)')
    entries2: dict = {}
    for port_s, i_s, j_s in re.findall(pat2, content):
        port = int(port_s)
        if port not in entries2:          # keep first (sub-slot 0 wins over sub-slot 1+)
            entries2[port] = (int(i_s), int(j_s))

    if entries2:
        # 2D: i=sacols_0=q_spatial, j=sacols_1=m
        result = [(0, 0)] * len(entries2)
        for port, (i, j) in entries2.items():
            result[port] = (j, i)   # (m, q_spatial)
        return result

    raise ValueError(
        f"No 'dram_output_pN = reduced_output[...]' lines found in {c_src_path}. "
        "Is this a conv top_level_sa.c with per-port output writes?"
    )


def gen_verify_py(port_to_mq: list, M: int, P: int, Q: int) -> str:
    """Return source of a self-contained per-deploy verify.py.

    PORT_TO_MQ is baked in as a literal list — no formula, no runtime inference.

    Gather is fully general for any Q spatial / temporal split:
      n_rows  = n_op // M        number of spatial Q slots (sacols_0 dimension)
      Qtiles  = Q // n_rows      temporal Q tile iterations in outer loop
      q_full  = q_spatial + n_rows * q_temporal
      offset  = p * Qtiles + q_temporal
    """
    n_op = len(port_to_mq)
    table_repr = repr(port_to_mq)
    return f'''\
#!/usr/bin/env python3
# verify.py — generated by generate_hacc_project.py, do not edit manually.
# Gathers FPGA output banks into the full tensor and compares to golden reference.
#
# Usage:  python3 verify.py <deploy_dir>
#
# PORT_TO_MQ[port] = (m, q_spatial)
#   m         = filter index (full M, reconstructed from SA spatial mapping)
#   q_spatial = spatial Q index within the SA column fanout (sacols_0)
#
# Gather formula (general for any Q spatial/temporal split):
#   n_rows  = n_op // M        number of spatial Q slots
#   Qtiles  = Q // n_rows      number of temporal Q tile iterations
#   q_full  = q_spatial + n_rows * q_temporal
#   offset  = p * Qtiles + q_temporal  (buffer index within each port)

import glob
import os
import struct
import sys

PORT_TO_MQ = {table_repr}
M, P, Q, N_OP = {M}, {P}, {Q}, {n_op}


def read_floats(path: str) -> list:
    with open(path, "rb") as f:
        raw = f.read()
    n = len(raw) // 4
    return list(struct.unpack(f"<{{n}}f", raw))


def main(deploy_dir: str) -> bool:
    in_dir  = os.path.join(deploy_dir, "input_data")
    out_dir = os.path.join(deploy_dir, "output_data")

    # Read golden reference
    gold_path = os.path.join(in_dir, "golden_out.bin")
    if not os.path.exists(gold_path):
        print(f"ERROR: golden not found: {{gold_path}}")
        sys.exit(1)
    gold = read_floats(gold_path)
    if len(gold) != M * P * Q:
        print(f"ERROR: golden has {{len(gold)}} floats, expected {{M*P*Q}}")
        sys.exit(1)

    # Read output banks (sorted numerically: dram_output_p0, p1, ...)
    pattern = os.path.join(out_dir, "dram_output_p*.bin")
    files = sorted(glob.glob(pattern),
                   key=lambda f: int(os.path.basename(f)
                                     .replace("dram_output_p", "")
                                     .replace(".bin", "")))
    if len(files) != N_OP:
        print(f"ERROR: expected {{N_OP}} output files, found {{len(files)}}")
        sys.exit(1)
    banks = [read_floats(f) for f in files]

    # Gather — general formula for any spatial/temporal Q split
    n_rows = N_OP // M          # spatial Q slots (sacols_0 dimension)
    Qtiles = Q // n_rows        # temporal Q tile iterations per spatial slot
    floats_per_port = P * Qtiles

    out_full = [0.0] * (M * P * Q)
    for port_idx, (m, q_spatial) in enumerate(PORT_TO_MQ):
        buf = banks[port_idx]
        if len(buf) != floats_per_port:
            print(f"WARNING: port {{port_idx}} has {{len(buf)}} floats, expected {{floats_per_port}}")
        for q_temporal in range(Qtiles):
            q = q_spatial + n_rows * q_temporal
            for p in range(P):
                offset = p * Qtiles + q_temporal
                out_full[m * P * Q + p * Q + q] = buf[offset]

    # Compare
    eps_abs, eps_rel = 1e-3, 1e-3
    errors = 0
    for i in range(M * P * Q):
        diff = abs(out_full[i] - gold[i])
        tol  = eps_abs + eps_rel * abs(gold[i])
        if diff > tol:
            print(f"  MISMATCH at [{{i}}]: HW={{out_full[i]:.6f}}  gold={{gold[i]:.6f}}"
                  f"  diff={{diff:.6f}}  tol={{tol:.6f}}")
            errors += 1
            if errors > 20:
                print("  (stopping after 20 errors)")
                break

    print()
    if errors == 0:
        print(f"SUCCESS: all {{M*P*Q}} outputs match the golden reference.")
    else:
        print(f"FAILURE: {{errors}} mismatches out of {{M*P*Q}} outputs.")
    return errors == 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: verify.py <deploy_dir>")
        sys.exit(1)
    ok = main(sys.argv[1])
    sys.exit(0 if ok else 1)
'''
