from .models import Interface


def gen_translator_v(iface: Interface) -> str:
    BASE, STEP = 0x10, 0x08
    addr_map = {arg: BASE + i * STEP for i, arg in enumerate(iface.scalar_args)}

    localparam_lines = ["    ADDR_AP_CTRL = 8'h00"]
    for arg in iface.scalar_args:
        localparam_lines.append(f"    ADDR_{arg.upper()} = 8'h{addr_map[arg]:02X}")
    localparam_lines += [
        "    WRIDLE  = 2'd0", "    WRDATA  = 2'd1",
        "    WRRESP  = 2'd2", "    WRRESET = 2'd3",
        "    RDIDLE  = 2'd0", "    RDDATA  = 2'd1",
        "    RDRESET = 2'd2",
        "    ADDR_BITS = C_S_AXI_CONTROL_ADDR_WIDTH",
    ]
    localparam_block = "localparam\n" + ",\n".join(localparam_lines) + ";"

    reg_decls = "\n".join(
        f"    reg [C_S_AXI_CONTROL_DATA_WIDTH-1:0] reg_{arg};"
        for arg in iface.scalar_args
    )
    output_assigns = "\n".join(
        f"    assign {arg} = reg_{arg};" for arg in iface.scalar_args
    )
    scalar_out_ports = "\n".join(
        f"    output wire [31:0] {arg}," for arg in iface.scalar_args
    )
    rdata_cases = "\n".join(
        f"                ADDR_{arg.upper()}: rdata <= reg_{arg}[31:0];"
        for arg in iface.scalar_args
    )
    reg_logic = "\n\n".join(
        f"    always @(posedge ap_clk) begin\n"
        f"        if (!ap_rst_n)\n"
        f"            reg_{arg} <= 0;\n"
        f"        else if (w_hs && waddr == ADDR_{arg.upper()})\n"
        f"            reg_{arg} <= (s_axi_control_WDATA & wmask) | (reg_{arg} & ~wmask);\n"
        f"    end"
        for arg in iface.scalar_args
    )

    # These lines contain Verilog {} so we keep them as plain strings
    wmask_line = (
        "    assign wmask = "
        "{ {8{s_axi_control_WSTRB[3]}}, {8{s_axi_control_WSTRB[2]}}, "
        "{8{s_axi_control_WSTRB[1]}}, {8{s_axi_control_WSTRB[0]}} };"
    )
    waddr_latch = (
        "        if (aw_hs) "
        "waddr <= {s_axi_control_AWADDR[ADDR_BITS-1:2], {2{1'b0}}};"
    )

    return f"""\
`timescale 1ns / 1ps
// AXI-Lite slave translator — auto-generated by generate_hacc_project.py
module top_level_translator #(
    parameter C_S_AXI_CONTROL_DATA_WIDTH = 32,
    parameter C_S_AXI_CONTROL_ADDR_WIDTH = 8,
    parameter C_WSTRB_WIDTH = 4
)(
    input  wire ap_clk,
    input  wire ap_rst_n,
    input       ap_ready,
    input       ap_done,
    // write address channel
    input  wire s_axi_control_AWVALID,
    input  wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0] s_axi_control_AWADDR,
    // write data channel
    input  wire s_axi_control_WVALID,
    input  wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0] s_axi_control_WDATA,
    input  wire [C_S_AXI_CONTROL_DATA_WIDTH/8-1:0] s_axi_control_WSTRB,
    // write response channel
    input  wire s_axi_control_BREADY,
    // read address channel
    input  wire s_axi_control_ARVALID,
    input  wire [C_S_AXI_CONTROL_ADDR_WIDTH-1:0] s_axi_control_ARADDR,
    input  wire s_axi_control_RREADY,
    // outputs
    output wire s_axi_control_AWREADY,
    output wire s_axi_control_WREADY,
    output wire [1:0] s_axi_control_BRESP,
    output wire s_axi_control_BVALID,
    output wire s_axi_control_ARREADY,
    output wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0] s_axi_control_RDATA,
    output wire [1:0] s_axi_control_RRESP,
    output wire s_axi_control_RVALID,
    // kernel argument registers
{scalar_out_ports}
    output wire ap_start
);

    {localparam_block}

    // local signals
    reg  [1:0]                                wstate = WRRESET;
    reg  [1:0]                                wnext;
    reg  [ADDR_BITS-1:0]                      waddr;
    wire [C_S_AXI_CONTROL_DATA_WIDTH-1:0]     wmask;
    wire                                       aw_hs;
    wire                                       w_hs;
    reg  [1:0]                                rstate = RDRESET;
    reg  [1:0]                                rnext;
    reg  [C_S_AXI_CONTROL_DATA_WIDTH-1:0]     rdata;
    wire                                       ar_hs;
    wire [ADDR_BITS-1:0]                       raddr;

{reg_decls}

    reg  busy_flag;
    reg  int_ap_start     = 1'b0;
    reg  int_auto_restart = 1'b0;
    reg  int_ap_ready     = 1'b0;
    reg  int_task_ap_done = 1'b0;
    reg  auto_restart_status = 1'b0;

    assign ap_start = int_ap_start;
{output_assigns}

    // ── AXI write FSM ──────────────────────────────────────────────────
    assign s_axi_control_AWREADY = (wstate == WRIDLE);
    assign s_axi_control_WREADY  = (wstate == WRDATA);
    assign s_axi_control_BRESP   = 2'b00;
    assign s_axi_control_BVALID  = (wstate == WRRESP);
{wmask_line}
    assign aw_hs = s_axi_control_AWVALID & s_axi_control_AWREADY;
    assign w_hs  = s_axi_control_WVALID  & s_axi_control_WREADY;

    always @(posedge ap_clk) begin
        if (!ap_rst_n) wstate <= WRRESET;
        else           wstate <= wnext;
    end
    always @(*) begin
        case (wstate)
            WRIDLE:  wnext = s_axi_control_AWVALID ? WRDATA : WRIDLE;
            WRDATA:  wnext = s_axi_control_WVALID  ? WRRESP : WRDATA;
            WRRESP:  wnext = s_axi_control_BREADY  ? WRIDLE : WRRESP;
            default: wnext = WRIDLE;
        endcase
    end
    always @(posedge ap_clk) begin
{waddr_latch}
    end

    // ── AXI read FSM ───────────────────────────────────────────────────
    assign s_axi_control_ARREADY = (rstate == RDIDLE);
    assign s_axi_control_RDATA   = rdata;
    assign s_axi_control_RRESP   = 2'b00;
    assign s_axi_control_RVALID  = (rstate == RDDATA);
    assign ar_hs = s_axi_control_ARVALID & s_axi_control_ARREADY;
    assign raddr = s_axi_control_ARADDR[ADDR_BITS-1:0];

    always @(posedge ap_clk) begin
        if (!ap_rst_n) rstate <= RDRESET;
        else           rstate <= rnext;
    end
    always @(*) begin
        case (rstate)
            RDIDLE:  rnext = s_axi_control_ARVALID ? RDDATA : RDIDLE;
            RDDATA:  rnext = (s_axi_control_RREADY & s_axi_control_RVALID) ? RDIDLE : RDDATA;
            default: rnext = RDIDLE;
        endcase
    end
    always @(posedge ap_clk) begin
        if (ar_hs) begin
            rdata <= 'b0;
            case (raddr)
                ADDR_AP_CTRL: begin
                    rdata[0] <= int_ap_start;
                    rdata[1] <= int_task_ap_done;
                    rdata[2] <= ~busy_flag;
                    rdata[3] <= int_ap_ready;
                    rdata[7] <= int_auto_restart;
                end
{rdata_cases}
            endcase
        end
    end

    // ── Register write logic ───────────────────────────────────────────
{reg_logic}

    // ── AP_CTRL logic ──────────────────────────────────────────────────
    always @(posedge ap_clk) begin
        if (!ap_rst_n) int_auto_restart <= 1'b0;
        else if (w_hs && waddr == ADDR_AP_CTRL && s_axi_control_WSTRB[0])
            int_auto_restart <= s_axi_control_WDATA[7];
    end
    always @(posedge ap_clk) begin
        if (!ap_rst_n) int_ap_start <= 1'b0;
        else if (w_hs && waddr == ADDR_AP_CTRL && s_axi_control_WSTRB[0] && s_axi_control_WDATA[0])
            int_ap_start <= 1'b1;
        else if (ap_ready)
            int_ap_start <= int_auto_restart;
    end
    always @(posedge ap_clk) begin
        if (!ap_rst_n) int_ap_ready <= 1'b0;
        else if (ap_ready && !int_auto_restart) int_ap_ready <= 1'b1;
        else if (ar_hs && raddr == ADDR_AP_CTRL) int_ap_ready <= 1'b0;
    end
    always @(posedge ap_clk) begin
        if (!ap_rst_n) busy_flag <= 1'b0;
        else if (w_hs && waddr == ADDR_AP_CTRL && s_axi_control_WSTRB[0] && s_axi_control_WDATA[0])
            busy_flag <= 1'b1;
        else if (ap_done && !int_auto_restart)
            busy_flag <= 1'b0;
    end
    always @(posedge ap_clk) begin
        if (!ap_rst_n) auto_restart_status <= 1'b0;
        else if (int_auto_restart) auto_restart_status <= 1'b1;
        else if (!busy_flag)        auto_restart_status <= 1'b0;
    end
    always @(posedge ap_clk) begin
        if (!ap_rst_n) int_task_ap_done <= 1'b0;
        else if (ap_done) int_task_ap_done <= 1'b1;
        else if (ar_hs && raddr == ADDR_AP_CTRL ||
                 (w_hs && waddr == ADDR_AP_CTRL && s_axi_control_WSTRB[0] && s_axi_control_WDATA[0]))
            int_task_ap_done <= 1'b0;
    end

endmodule
"""
