from .models import Interface, _port_str


def gen_wrapper_v(iface: Interface) -> str:
    static_ports = [
        "  input  ap_clk",
        "  input  ap_rst_n",
        "  output ap_done",
        "  output ap_ready",
        "  input  cache_reset",
        "  input  s_axi_control_AWVALID",
        "  input  [7:0] s_axi_control_AWADDR",
        "  input  s_axi_control_WVALID",
        "  input  [31:0] s_axi_control_WDATA",
        "  input  [3:0] s_axi_control_WSTRB",
        "  input  s_axi_control_BREADY",
        "  input  s_axi_control_ARVALID",
        "  input  [7:0] s_axi_control_ARADDR",
        "  input  s_axi_control_RREADY",
        "  output s_axi_control_AWREADY",
        "  output s_axi_control_WREADY",
        "  output [1:0] s_axi_control_BRESP",
        "  output s_axi_control_BVALID",
        "  output s_axi_control_ARREADY",
        "  output [31:0] s_axi_control_RDATA",
        "  output [1:0] s_axi_control_RRESP",
        "  output s_axi_control_RVALID",
    ]
    axi_port_strs = [_port_str(p.direction, p.width, p.name) for p in iface.axi_ports]
    port_block = ",\n".join(static_ports + axi_port_strs)

    scalar_wire_block = "\n".join(
        f"  wire [31:0] {arg};" for arg in iface.scalar_args
    )
    translator_arg_conns = "\n".join(
        f"    .{arg}({arg})," for arg in iface.scalar_args
    )
    core_scalar_block = "\n".join(
        f"    .{arg}({arg})," for arg in iface.scalar_args
    )
    core_axi_list = [f"    .{p.name}({p.name})" for p in iface.axi_ports]
    core_axi_block = ",\n".join(core_axi_list)

    return f"""\
`timescale 1ns / 1ps
// Vitis-compatible wrapper for Bambu top_level
// Kernel name: panda   (used in script_to_xo.tcl and harness.cpp)
// Generated by generate_hacc_project.py — do not edit manually
module panda (
{port_block}
);

  wire sig_done;
  wire ap_start_lvl;

{scalar_wire_block}

  // Rising-edge detector: Bambu needs a 1-cycle start_port pulse
  reg  ap_start_q;
  always @(posedge ap_clk) ap_start_q <= ap_start_lvl;
  wire start_port_pulse = ap_start_lvl & ~ap_start_q;

  // ap_ready: 1 cycle after start_port (tells XRT job was accepted)
  reg  ap_ready_r;
  always @(posedge ap_clk) ap_ready_r <= start_port_pulse;
  assign ap_ready = ap_ready_r;
  assign ap_done  = sig_done;

  // AXI-Lite translator
  top_level_translator translator (
    .ap_clk(ap_clk),
    .ap_rst_n(ap_rst_n),
    .ap_done(sig_done),
    .ap_ready(start_port_pulse),
    .ap_start(ap_start_lvl),
    .s_axi_control_AWVALID(s_axi_control_AWVALID),
    .s_axi_control_AWADDR(s_axi_control_AWADDR),
    .s_axi_control_WVALID(s_axi_control_WVALID),
    .s_axi_control_WDATA(s_axi_control_WDATA),
    .s_axi_control_WSTRB(s_axi_control_WSTRB),
    .s_axi_control_BREADY(s_axi_control_BREADY),
    .s_axi_control_ARVALID(s_axi_control_ARVALID),
    .s_axi_control_ARADDR(s_axi_control_ARADDR),
    .s_axi_control_RREADY(s_axi_control_RREADY),
    .s_axi_control_AWREADY(s_axi_control_AWREADY),
    .s_axi_control_WREADY(s_axi_control_WREADY),
    .s_axi_control_BRESP(s_axi_control_BRESP),
    .s_axi_control_BVALID(s_axi_control_BVALID),
    .s_axi_control_ARREADY(s_axi_control_ARREADY),
    .s_axi_control_RDATA(s_axi_control_RDATA),
    .s_axi_control_RRESP(s_axi_control_RRESP),
    .s_axi_control_RVALID(s_axi_control_RVALID),
{translator_arg_conns}
    .ap_start(ap_start_lvl)
  );

  // Bambu core (top_level.v — unmodified)
  top_level core (
    .clock(ap_clk),
    .reset(ap_rst_n),
    .start_port(start_port_pulse),
    .cache_reset(cache_reset),
{core_scalar_block}
    .done_port(sig_done),
{core_axi_block}
  );

endmodule
"""
